services:
  web:
    build: .
    env_file:
      - .env
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - fast_network
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    env_file:
      - .env
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - fast_messages_service:/var/lib/postgresql/data
    networks:
      - fast_network
    ports:
      - "5432:5432"

  telegram_bot:
    build:
      context: ./telegram_bot
    env_file:
      - .env
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    volumes:
      - ./telegram_bot:/app
    networks:
      - fast_network

networks:
  fast_network:
    driver: bridge

volumes:
  fast_messages_service:
    driver: local

